# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfa08909c4a82de7d4ca4b55f6845387cccdd0d639aed630adff7a21d8886f79efb8fdab013d6de56fc4a9428d9361e3e99d1ed73a47c84ee68351e378953d71

test:
  secret_key_base: c19a794bce48bc11066d7fcc249c43f4716ccfe4edb259c7532e5af9d4597096a4e0b117d345fb95ab2490bcd014b512df000b2a96c61edd6dc19e438f36d984

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
